[PRM-224] - added reasonableExcuses form error
hmrc/penalties-appeals-frontend pull request #13
Opened 2021-05-17 14:22 UTC by BackRowOla

2021-05-17 14:23 UTC, BackRowOla commented
![Screenshot 2021-05-17 at 15 23 25](https://user-images.githubusercontent.com/56401572/118504906-d5954500-b723-11eb-8e8b-6461852e4987.png)

2021-05-17 15:03 UTC, LewisMitchell requested changes
Looks good to me, just a few changes.

2021-05-17 15:03 UTC, LewisMitchell commented on conf/messages
> +error.summary.title = There is a problem
As part of having an error on the page - we need to modify the page title to prefix `Error: `
I've done this in https://github.com/hmrc/penalties-appeals-frontend/commit/42792af03390c359b9bb8f8f70cf34cd1dde5bd5

2021-05-17 15:03 UTC, LewisMitchell commented on conf/messages
> +reasonableExcuses.error.required = Select the reason for missing the VAT deadline
Could you copy these messages over to messages.cy

2021-05-17 15:03 UTC, LewisMitchell commented on test/controllers/ReasonableExcuseControllerSpec.scala
> +        status(result) shouldBe BAD_REQUEST
Could you assert what's on the page? Like making sure `"There is a problem"` and `"Select the reason for missing the VAT deadline"` is on the page?
I know it's not really the controllers job - but it saves doing it in the view.

2021-05-18 07:49 UTC, LewisMitchell commented
![image](https://user-images.githubusercontent.com/53828896/118612647-84319800-b7ad-11eb-976e-b611c21ec548.png)
Revised.

2021-05-18 07:50 UTC, LewisMitchell commented
Looks good, just needs a message copying to messages.cy

```
# Errors
# ----------------------------------------------------------
error.prefix = Error:
```

2021-05-18 07:51 UTC, LewisMitchell requested changes
Just the messages.

2021-05-18 08:43 UTC, LewisMitchell approved these changes
Fine by me just waiting for #12

2021-05-18 09:28 UTC, AndrewRButcher approved these changes

2021-05-18 11:59 UTC, merged