[PRM-648] - Added callback functionality for upload service
hmrc/penalties-appeals-frontend pull request #136
Opened 2021-09-17 10:31 UTC by LewisMitchell

2021-09-17 11:50 UTC, LewisMitchell commented
Needs https://github.com/hmrc/build-jobs/pull/9368 to be merged first - tests failing is a known issue

2021-09-20 09:00 UTC, LewisMitchell commented
rebuild

2021-09-20 09:57 UTC, AndrewRButcher requested changes

2021-09-20 09:57 UTC, AndrewRButcher commented on app/models/upload/UploadJourney.scala
> +  }
Can we add a test for this reads as it is not covered currently

2021-09-20 10:11 UTC, AndrewRButcher approved these changes

2021-09-20 10:12 UTC, merged