[PRM-643] Update CYA Page with filenames
hmrc/penalties-appeals-frontend pull request #149
Opened 2021-09-23 11:46 UTC by JBlacklaws

2021-09-23 12:11 UTC, LewisMitchell requested changes
AT's fail, most likely because my https://github.com/hmrc/penalties-appeals-frontend/pull/147 PR isn't in.
Just some changes to refactor the implementation a bit more

2021-09-23 12:11 UTC, LewisMitchell commented on app/controllers/CheckYourAnswersController.scala
> +          }
You could replace this check with this:
```
            logger.debug(s"[CheckYourAnswersController][onPageLoad] Loading check your answers page")
            for {
              previousUploads <- uploadJourneyRepository.getUploadsForJourney(request.session.get(SessionKeys.journeyId))
            } yield {
              val previousUploadsFileName = previousUploads.map(_.map(file => file.uploadDetails.map(details => details.fileName)))
              val x = previousUploadsFileName.getOrElse(Seq.empty).collect {
                case Some(x) => x
              }.mkString(", ")
              val answersFromSession = sessionAnswersHelper.getAllTheContentForCheckYourAnswersPage(if (x.isEmpty) None else Some(x))
              Ok(checkYourAnswersPage(answersFromSession))
            }
```

2021-09-23 12:11 UTC, LewisMitchell commented on app/controllers/CheckYourAnswersController.scala
> +          }
This way saves the 2 different scenarios where the parameter is Some(x) or None

2021-09-23 13:29 UTC, LewisMitchell requested changes

2021-09-23 13:29 UTC, LewisMitchell commented on app/controllers/CheckYourAnswersController.scala
> +            val x = previousUploadsFileName.getOrElse(Seq.empty).collect {
This is my mistake :sorry: . But can you make `x` to be something like `fileNames`?

2021-09-23 13:29 UTC, LewisMitchell commented on app/controllers/CheckYourAnswersController.scala
> +            val x = previousUploadsFileName.getOrElse(Seq.empty).collect {
This is my mistake :sorry: . But can you make `x` to be something like `fileNames`?

2021-09-23 13:35 UTC, LewisMitchell commented
Also can we remove evidenceFileName now? We shouldn't need it anymore?

2021-09-23 13:59 UTC, JBlacklaws commented
Yeah, we should get rid of that SessionKey, but that's uncovered a bunch of TODOs I should have handled, so I'll need to clear those out!

2021-09-24 12:13 UTC, LewisMitchell requested changes
This also needs an AT change, something either temporary or more permanent.
See AppealAgainstObligation flow - Changing Values scenario for more details.
It uploads another file and the CYA page displays the old file and new file (something we will remove later - but needs to be addressed in the AT's now)

2021-09-24 16:28 UTC, LewisMitchell approved these changes

2021-09-24 16:29 UTC, LewisMitchell commented
AT change https://github.com/hmrc/penalties-acceptance-tests/pull/80

2021-09-27 09:09 UTC, merged