[PRM-795] Updated routing for Upload list page
hmrc/penalties-appeals-frontend pull request #185
Opened 2021-11-02 15:57 UTC by JBlacklaws

2021-11-03 08:13 UTC, LewisMitchell requested changes

2021-11-03 08:13 UTC, LewisMitchell commented on app/navigation/Navigation.scala
> +    UploadAnotherDocumentPage -> ((_,_,_) => routes.OtherReasonController.onPageLoadUploadList(NormalMode))
Not that this is an option yet, but you may want to consider adding a page for where to go from the 'You have uploaded X files' i.e. adding UploadListPage and then adding some functionality that would route to the making a late appeal or CYA page when the user says no or to the add another page if the user says yes to adding another document

2021-11-03 08:13 UTC, LewisMitchell commented on app/navigation/Navigation.scala
> +    UploadAnotherDocumentPage -> ((_,_,_) => routes.OtherReasonController.onPageLoadUploadList(CheckMode))
For CheckMode, if the user selects No - we go straight back to the CYA page.
if the user selects Yes - we go to add another document passing the mode through

2021-11-03 08:13 UTC, LewisMitchell commented on app/controllers/OtherReasonController.scala
> +        val nextPageWithUpload = navigation.nextPage(UploadFirstDocumentPage, mode)
I don't think you need this, we have logic that will already redirect the user on success and failure

2021-11-03 08:13 UTC, LewisMitchell commented on app/views/reasonableExcuseJourneys/other/noJs/UploadFirstDocumentPage.scala.html
> +            <a href="@nextPageWithUpload" class="govuk-button">@messages("otherReason.uploadEvidence.noJs.button.uploadFile")</a>
<a> tags do not submit the form. They are hyperlinks that redirects the user to a page without submitting the form itself. You shouldn't need to actually pass anything here and can be removed.

2021-11-03 08:13 UTC, LewisMitchell commented on app/views/reasonableExcuseJourneys/other/noJs/UploadFirstDocumentPage.scala.html
> +    nextPageWithUpload: String,
We don't need this as the logic is pre-existing to route the user onward

2021-11-03 08:13 UTC, LewisMitchell commented on conf/app.routes
> +GET        /uploaded-documents/change                               controllers.OtherReasonController.onPageLoadUploadList(mode: Mode = CheckMode)
This is much better naming than /upload-complete 😊

2021-11-03 08:13 UTC, LewisMitchell commented on it/controllers/OtherReasonControllerISpec.scala
> +      val request = await(controller.onPageLoadUploadList(NormalMode)(fakeRequestWithCorrectKeys))
Could you change the "GET /upload-complete" to the correct URL:
https://github.com/hmrc/penalties-appeals-frontend/pull/185/files#diff-1f25331e29c9f185c275d716035c984e6f80e928d6470edf5c800ab02f647228R508

2021-11-03 08:13 UTC, LewisMitchell commented on it/controllers/OtherReasonControllerISpec.scala
> +      val request = await(buildClientForRequestToApp(uri = "/upload-another-document").get())
This should be "/uploaded-documents"

2021-11-03 08:13 UTC, LewisMitchell commented on test/controllers/OtherReasonControllerSpec.scala
>      "onPageLoadForUploadComplete" should {
Could you change this to "onPageLoadUploadList"

2021-11-03 08:13 UTC, LewisMitchell commented on test/views/UploadFirstDocumentPageSpec.scala
> +    val uploadAction = controllers.routes.OtherReasonController.onPageLoadForAnotherFileUpload(NormalMode).url
I don't think you need this

2021-11-03 08:13 UTC, LewisMitchell commented on test/views/UploadFirstDocumentPageSpec.scala
> +      uploadFirstDocumentPage.apply(uploadAction, mockUpscanInitiateResponseModel, form, noUploadAction)(request, implicitly, implicitly)
As above

2021-11-03 15:56 UTC, LewisMitchell requested changes

2021-11-03 15:56 UTC, LewisMitchell commented on app/navigation/Navigation.scala
> +    UploadAnotherDocumentPage -> ((answer, _, _) => routeToAdditionalUploadOrCYAPage(CheckMode, answer))
I think once the user has uploaded another document and they are in CheckMode, that they should be routed to the upload list page?

2021-11-03 15:56 UTC, LewisMitchell commented on app/navigation/Navigation.scala
> +    UploadAnotherDocumentPage -> ((answer, _, _) => routeToAdditionalUploadOrCYAPage(CheckMode, answer))
A case for FileListPage should be added so it then calls  routeForUploadList

2021-11-03 15:56 UTC, LewisMitchell commented on app/navigation/Navigation.scala
> +  }
I don't think you need `routeToAdditionalUploadOrCYAPage` as its practically duplicating `routeForUploadList`

2021-11-04 15:33 UTC, LewisMitchell commented
Also needs rebasing now

2021-11-05 10:18 UTC, LewisMitchell commented
Normal mode - No additional

https://user-images.githubusercontent.com/53828896/140495041-9d14f42f-97cb-4d0c-809f-8b75da98fe06.mov


Normal mode - additional

https://user-images.githubusercontent.com/53828896/140495064-bd51289e-f686-403b-8f80-13d78f483da0.mov


Check mode - No additional

https://user-images.githubusercontent.com/53828896/140495077-e2d03d96-2eca-4ad1-9fea-da0b4da515ee.mov


Check mode - additional

https://user-images.githubusercontent.com/53828896/140495099-1c3963bc-1bc8-49a2-8e86-a96b331149d7.mov


Normal mode - No additional - obligation

https://user-images.githubusercontent.com/53828896/140495191-31cd73bd-752d-47ca-bd35-809144392c63.mov


Normal mode - additional - obligation

https://user-images.githubusercontent.com/53828896/140495219-879f80e1-bcfd-4d0d-ab4f-aee614baf9c3.mov


Check mode - No additional - obligation

https://user-images.githubusercontent.com/53828896/140495243-fc491f1f-bb9d-46d8-9561-fdc45a6dc80f.mov


Check mode - additional - obligation

https://user-images.githubusercontent.com/53828896/140495265-780ca90e-2229-4c09-96de-76e7fe1a9702.mov

2021-11-08 09:42 UTC, AndrewRButcher approved these changes

2021-11-08 09:43 UTC, merged