[PRM-283] - Added late appeal routing for crime flow
hmrc/penalties-appeals-frontend pull request #27
Opened 2021-06-09 12:33 UTC by LewisMitchell

2021-06-09 12:33 UTC, LewisMitchell commented
AT change: https://github.com/hmrc/penalties-acceptance-tests/pull/21

2021-06-10 09:28 UTC, AndrewRButcher requested changes

2021-06-10 09:28 UTC, AndrewRButcher commented on app/navigation/Navigation.scala
> +    if(dateSentParsed.isBefore(dateTimeNow.minusDays(daysResultingInLateAppeal)) && userRequest.session.get(SessionKeys.lateAppealReason).isEmpty) {
this is causing the late appeal page to be skipped if the user has already entered a reason and then goes back

https://user-images.githubusercontent.com/6122384/121500750-7fd85380-c9d6-11eb-9055-024be8217a40.mov

2021-06-10 14:18 UTC, AndrewRButcher commented on app/navigation/Navigation.scala
> +    if(dateSentParsed.isBefore(dateTimeNow.minusDays(daysResultingInLateAppeal)) && userRequest.session.get(SessionKeys.lateAppealReason).isEmpty) {
fix implemented in https://github.com/hmrc/penalties-appeals-frontend/pull/30

2021-06-10 15:45 UTC, closed without merging