[PRM-1507] Removed old API data and feature switch, along with changing LocalDateTime to LocalDate
hmrc/penalties-appeals-frontend pull request #329
Opened 2022-07-06 13:03 UTC by JBlacklaws

2022-07-07 07:49 UTC, LewisMitchell requested changes
Looks good, the file upload changes need to be reverted

2022-07-07 07:49 UTC, LewisMitchell commented on app/models/AppealData.scala
> +  implicit val format: Format[AppealData[LocalDate]] = Json.format[AppealData[LocalDate]]
We can revert this back to how it was before, by removing the type parameter ([A]) from the case class and changing startDate: A to startDate: LocalDate etc.

2022-07-07 07:49 UTC, LewisMitchell commented on app/models/appeals/AppealSubmission.scala
> +                             dateOfAppeal: LocalDate,
Checking the API, the dateOfAppeal is a LocalDateTime

2022-07-07 07:49 UTC, LewisMitchell commented on app/models/upload/UploadDetails.scala
> +                          uploadTimestamp: LocalDate,
We get this from Upscan, this isn't to do with the feature switch

2022-07-07 07:49 UTC, LewisMitchell commented on app/models/upload/UploadJourney.scala
> +                           lastUpdated: LocalDate = LocalDate.now(),
This is not to do with the feature switch, keep it as LocalDateTime

2022-07-07 12:14 UTC, LewisMitchell submitted a review, later dismissed

2022-07-07 12:14 UTC, LewisMitchell commented on app/models/upload/UploadDetails.scala
> -import java.time.LocalDate
You can remove the LocalDate import now

2022-07-07 12:14 UTC, LewisMitchell commented on test/controllers/internal/UpscanCallbackControllerSpec.scala
> +import java.time.{LocalDate, LocalDateTime}
You can remove the LocalDate import now

2022-07-07 12:14 UTC, LewisMitchell commented on test/helpers/SessionAnswersHelperSpec.scala
> +import java.time.{LocalDate, LocalDateTime}
You can remove the LocalDate import now

2022-07-07 12:14 UTC, LewisMitchell commented on test/services/AppealServiceSpec.scala
> +import java.time.{LocalDate, LocalDateTime}
You can remove the LocalDate import now

2022-07-11 10:26 UTC, AndrewRButcher approved these changes

2022-07-11 10:35 UTC, merged