PRM-1553 JS journey, updated error message content
hmrc/penalties-appeals-frontend pull request #334
Opened 2022-07-14 07:51 UTC by ruthdas03

2022-07-15 11:14 UTC, ruthdas03 commented
<img width="765" alt="Screenshot 2022-07-15 at 12 09 42" src="https://user-images.githubusercontent.com/86231805/179212002-f7f3cd76-afa9-4078-8da7-88b2c40e4578.png">


<img width="540" alt="Screenshot 2022-07-15 at 12 09 29" src="https://user-images.githubusercontent.com/86231805/179211945-0203c918-008d-45ed-b33c-613fe8101612.png">

<img width="704" alt="Screenshot 2022-07-15 at 12 12 02" src="https://user-images.githubusercontent.com/86231805/179212365-defb29ae-6d31-428b-b1a3-62b60ebc38d8.png">

2022-07-15 14:21 UTC, LewisMitchell requested changes

2022-07-18 07:42 UTC, LewisMitchell commented on app/helpers/UpscanMessageHelper.scala
> +      }
Hmmm,  come to think of it I don't think there is a way to do this

2022-07-18 08:40 UTC, LewisMitchell approved these changes
LGTM

2022-07-18 08:40 UTC, merged