PRM-1577 New page for “cover both penalties”
hmrc/penalties-appeals-frontend pull request #338
Opened 2022-07-20 14:02 UTC by ruthdas03

<img width="716" alt="Screenshot 2022-07-20 at 14 27 54" src="https://user-images.githubusercontent.com/86231805/180001698-aa2b3abd-c42e-46a2-bb2f-9936eb14416c.png">

2022-07-20 14:44 UTC, LewisMitchell requested changes
There's no way to get to the page, I know routing is a separate sub-task however we should be able to hit the page manually using a URL. Could you add a controller method and route to show the page?

2022-07-20 14:44 UTC, LewisMitchell commented on app/views/AppealCoverBothPenaltiesPage.scala.html
> +        <p class="govuk-body">@messages("appealCoverBothPenalties.p1")</p>
Could you unindent this so it lines up with @govuk-button

2022-07-21 07:28 UTC, LewisMitchell requested changes

2022-07-21 07:28 UTC, LewisMitchell commented on app/controllers/AppealCoverPenaltiesController.scala
> +}
Is it easier to use the PenaltySelectionController instead of creating a new one?

2022-07-21 08:38 UTC, LewisMitchell commented on app/controllers/AppealCoverPenaltiesController.scala
> +}
Maybe that's best because we can don't have lots of single method classes?

2022-07-21 09:15 UTC, LewisMitchell commented on app/controllers/AppealCoverPenaltiesController.scala
> +}
Do you still need this controller?

2022-07-21 09:17 UTC, LewisMitchell requested changes

2022-07-21 09:17 UTC, LewisMitchell commented on conf/app.routes
> +GET        /appeal-cover-for-both-penalties                    controllers.AppealCoverPenaltiesController.onPageLoadForAppealCoverBothPenalties()
This should point to the existing controller (PenaltySelectionController)

2022-07-21 11:38 UTC, LewisMitchell requested changes

2022-07-21 11:38 UTC, LewisMitchell commented on app/views/AppealCoverBothPenaltiesPage.scala.html
> +    backLinkEnabled = false) {
The back link should be enabled.
I know routing is going to be done in a separate PR, but that should be related to routing to and from these pages, any interaction within these pages should be dealt with now.
An example can be found in: #337

2022-07-21 11:39 UTC, LewisMitchell commented
Could you also rebase when you get chance?

2022-07-21 14:10 UTC, LewisMitchell requested changes

2022-07-21 14:10 UTC, LewisMitchell commented on app/views/AppealCoverBothPenaltiesPage.scala.html
> +@(pageMode: PageMode, nextPage: String, penaltyInformation: String)(implicit messages: Messages, appConfig: AppConfig, userRequest: UserRequest[_])
This page doesn't need penaltyInformation

2022-07-21 14:10 UTC, LewisMitchell commented on app/models/pages/Page.scala
> +case object AppealCoverBothPenaltiesPage extends Page
Could you add this to the allPages val

2022-07-21 14:10 UTC, LewisMitchell commented on conf/app.routes
> +POST       /appeal-cover-for-both-penalties/change             controllers.PenaltySelectionController.onPageLoadForAppealCoverBothPenalties(mode: Mode = CheckMode)
POSTs are only needed if you submit forms

2022-07-21 15:03 UTC, LewisMitchell requested changes
I noticed I missed something from my other PR regarding the back link, could you apply the same change here? :sorry:

2022-07-21 15:15 UTC, ruthdas03 commented
> back link



> I noticed I missed something from my other PR regarding the back link, could you apply the same change here? :sorry:

Is it about enabling the back link, I'm not too sure.

2022-07-22 07:30 UTC, LewisMitchell approved these changes

2022-07-22 07:56 UTC, merged