PRM-2244 handle 207s received due document storage failures on multi appeal
hmrc/penalties-appeals-frontend pull request #408
Opened 2023-01-26 10:57 UTC by AndrewRButcher

2023-01-26 11:01 UTC, LewisMitchell requested changes

2023-01-26 11:01 UTC, LewisMitchell commented on test/services/AppealServiceSpec.scala
> +        .thenReturn(Future.successful(HttpResponse(OK, "PR-1234")))
What if one was MULTI_STATUS and the other was ISE, then it would show the error page, see above comment for fix

2023-01-26 11:28 UTC, AndrewRButcher commented on app/services/AppealService.scala
>          sendAuditIfDuplicatesExist(uploads)
So I left this open as we could have the case where 1 submission comes back with 207 and the other comes back with 502 (or other error codes) due to connectivity issues (or similar) in this case a submission will have been made to PEGA so we need to show the confirmation

2023-01-26 13:08 UTC, LewisMitchell requested changes

2023-01-26 13:08 UTC, LewisMitchell commented on app/services/AppealService.scala
> +        logger.debug("[AppealService][multipleAppeal] - Second penalty was appealed successfully, first penalty had issues")
Should this be, 'both penalties had issues'?

2023-01-26 13:08 UTC, LewisMitchell commented on app/services/AppealService.scala
> +        firstResponse.status == OK
Don't think this is needed? ref: firstResponse.status == OK

2023-01-26 13:08 UTC, LewisMitchell commented on test/services/AppealServiceSpec.scala
> +          println(logMessage)
Could you remove this?

2023-01-26 13:08 UTC, LewisMitchell commented on test/services/AppealServiceSpec.scala
> +          println(logMessage)
Could you remove this?

2023-01-26 13:08 UTC, LewisMitchell commented on app/services/AppealService.scala
> +        logPartialFailureOfMultipleAppeal(firstResponse, secondResponse, vrn, dateFrom, dateTo)(didLPP1Fail = true,  wasPartSuccess = secondResponse.status == MULTI_STATUS)
```suggestion
        logPartialFailureOfMultipleAppeal(firstResponse, secondResponse, vrn, dateFrom, dateTo)(didLPP1Fail = true, wasPartSuccess = secondResponse.status == MULTI_STATUS)
```

2023-01-27 11:09 UTC, LewisMitchell approved these changes

2023-01-27 11:12 UTC, merged