[PRM-2354] Moved header outside out radio on cancel vat page
hmrc/penalties-appeals-frontend pull request #424
Opened 2023-03-06 11:50 UTC by JBlacklaws

2023-03-06 15:34 UTC, JBlacklaws commented
Desktop: 
![Screenshot 2023-03-06 at 10 58 35](https://user-images.githubusercontent.com/58850837/223156546-4e011201-033e-4291-bf04-fa42b92df6d0.png)

Mobile:
![Screenshot 2023-03-06 at 11 08 14](https://user-images.githubusercontent.com/58850837/223156577-d26d00d8-48e5-4f41-bd9c-2fe5ff73c394.png)

HTML:
![Screenshot 2023-03-06 at 10 59 34](https://user-images.githubusercontent.com/58850837/223156614-c38d1d17-ffe9-48f0-8468-c07a698a9919.png)

2023-03-07 09:58 UTC, LewisMitchell requested changes

2023-03-07 09:58 UTC, LewisMitchell commented on app/views/CancelVATRegistrationPage.scala.html
> +    @pageHeader(messages("cancelVATRegistration.headingAndTitle"))
The caption should be a h2 outside of the fieldset

2023-03-07 09:58 UTC, LewisMitchell commented on app/views/CancelVATRegistrationPage.scala.html
> +            legendContent = "",
The legend should still contain the page heading

2023-03-07 09:58 UTC, LewisMitchell commented on app/views/CancelVATRegistrationPage.scala.html
The latest design can be found here: https://design.tax.service.gov.uk/hmrc-design-patterns/page-heading/#options-example-legends-as-page-headings-with-subheading

```
<h2>caption here</h2>
<fieldset>
<legend>
<h1>page heading here</h1>
</legened>
</fieldset>
```

I believe this should be applied on several pages that make use of a fieldset (or radios in this case)

2023-03-10 08:29 UTC, LewisMitchell commented
Could you rebase again please?

2023-03-10 09:53 UTC, LewisMitchell requested changes

2023-03-10 09:53 UTC, LewisMitchell commented on app/views/CancelVATRegistrationPage.scala.html
> +    @pageHeader(messages("cancelVATRegistration.headingAndTitle"), showPageHeader = false)
Maybe `showPageHeader` isn't needed? Could we change the first parameter of the page header to be Option[String]?

2023-03-10 09:53 UTC, LewisMitchell commented on app/views/components/pageHeader.scala.html
> +@if(showPageHeader) {
Further to the above, if we change pageHeader to Option[String] we could get rid of the showPageHeader param? What do you think?

2023-03-10 09:53 UTC, LewisMitchell commented on app/views/components/pageHeader.scala.html
> +@if(showPageHeader) {
This check would then become pageHeader.isDefined

2023-03-10 09:53 UTC, LewisMitchell commented on app/views/CancelVATRegistrationPage.scala.html
>      formHasErrors = form.errors.nonEmpty,
I believe date inputs also use fieldsets so we made need to change that, do we want to do that in this PR or a new subtask?

2023-03-10 09:53 UTC, LewisMitchell commented on app/views/components/radios.scala.html
>  @legend = {
This isn't being used, according to the HMRC design system - there should be a `<h1>` inside the `<legend>` I suspect it is to do with the check on line 48.

2023-03-10 09:53 UTC, LewisMitchell commented on app/views/components/radios.scala.html
>  @legend = {
![image](https://user-images.githubusercontent.com/53828896/224283880-1bc50dff-48a8-492c-8712-a7513285cbc1.png)

2023-03-10 09:53 UTC, LewisMitchell commented on app/views/components/radios.scala.html
>  @legend = {
Be careful though as not all pages with fieldsets have legends which contain `<h1>` within them. For example the `/multiple-penalties-for-this-period` page has a h1 that isn't in the fieldset

2023-03-10 11:37 UTC, LewisMitchell commented
Will need to rebase also due to #426 going in

2023-03-10 15:54 UTC, LewisMitchell requested changes

2023-03-10 15:54 UTC, LewisMitchell commented on app/views/components/radios.scala.html
>  @govukRadios(Radios(
Could you rename showPenaltyInformation to be something like legendAsPageHeading?

2023-03-10 15:54 UTC, LewisMitchell commented on app/views/components/inputDate.scala.html
>          legendAsPageHeading: Boolean = false)(implicit messages: Messages, userRequest: UserRequest[_], appConfig: AppConfig)
Do we need showPenaltyInformation now? It seems redundant as we never show penalty information within this component now

2023-03-10 16:14 UTC, LewisMitchell requested changes

2023-03-10 16:14 UTC, LewisMitchell commented on app/views/components/inputDate.scala.html
> +        showPenaltyInformation: Boolean = true)(implicit messages: Messages, userRequest: UserRequest[_], appConfig: AppConfig)
Should this be legendAsPageHeading?

2023-03-10 18:14 UTC, LewisMitchell requested changes

2023-03-13 09:43 UTC, LewisMitchell approved these changes

2023-03-13 09:43 UTC, merged