[PRM-2395] Allow users to reload the confirmation page
hmrc/penalties-appeals-frontend pull request #436
Opened 2023-03-16 12:48 UTC by JBlacklaws

2023-03-16 14:42 UTC, JBlacklaws commented
https://user-images.githubusercontent.com/58850837/225652841-5bf3b2b0-a78c-404c-9921-5d949d0580bc.mov

2023-03-21 09:09 UTC, AndrewRButcher requested changes
One small change suggested

2023-03-21 09:09 UTC, AndrewRButcher commented on app/controllers/CheckYourAnswersController.scala
> +          )
```suggestion
            List(
              (SessionKeys.confirmationAppealType, confirmationAppealType),
              (SessionKeys.confirmationStartDate, confirmationStartDate),
              (SessionKeys.confirmationEndDate, confirmationEndDate),
              (SessionKeys.confirmationObligation, confirmationObligation),
              (SessionKeys.confirmationMultipleAppeals, confirmationMultipleAppeals),
              (SessionKeys.confirmationIsAgent, confirmationIsAgent)): _*
          )
```

2023-03-21 10:05 UTC, AndrewRButcher commented
Also needs rebasing

2023-03-21 11:18 UTC, AndrewRButcher approved these changes

2023-03-21 11:19 UTC, merged