Prm 3176 removed obligation joruney
hmrc/penalties-appeals-frontend pull request #548
Opened 2024-01-05 10:21 UTC by RoheelArshad

2024-01-05 14:20 UTC, AndrewRButcher requested changes
Couple of extra comments:
1. Can any views remaining after amendments in `views.obligation` be moved to `views.findOutHowToAppeal`
2. ObligationAppealInformation model (and any associated uses)can be removed

2024-01-05 14:20 UTC, AndrewRButcher commented on app/controllers/HonestyDeclarationController.scala
>        case (Some(reasonableExcuse), Some(dueDate), Some(startDate), Some(endDate), isObligation: Boolean) =>
this param should not be needed anymore (only users with a reasonable excuse can access the honesty declaration page
```suggestion
      ) match {
      case (Some(reasonableExcuse), Some(dueDate), Some(startDate), Some(endDate)) =>
```

2024-01-05 14:20 UTC, AndrewRButcher commented on app/controllers/ViewAppealDetailsController.scala
> +                    if (userAnswers.getAnswer[Boolean](SessionKeys.isFindOutHowToAppeal).isDefined || userRequest.answers.getAnswer[String](SessionKeys.reasonableExcuse).contains("other")) {
```suggestion
                    if (userRequest.answers.getAnswer[String](SessionKeys.reasonableExcuse).contains("other")) {
```

2024-01-05 14:20 UTC, AndrewRButcher commented on app/controllers/YouCanAppealPenaltyController.scala
>  package controllers
I believe this controller and appropriate view view can be removed

2024-01-05 14:20 UTC, AndrewRButcher commented on app/helpers/IsLateAppealHelper.scala
> +    if (userRequest.answers.getAnswer[Boolean](SessionKeys.isFindOutHowToAppeal).isEmpty){
Remove Line 30 & 44 -46

2024-01-05 14:20 UTC, AndrewRButcher commented on app/helpers/SessionAnswersHelper.scala
> +    if (!reasonableExcuse.equals("other") && !userRequest.answers.getAnswer[Boolean](SessionKeys.isFindOutHowToAppeal).contains(true)) {
```suggestion
    if (!reasonableExcuse.equals("other")) {
```

2024-01-05 14:20 UTC, AndrewRButcher commented on app/navigation/Navigation.scala
> +      && userRequest.answers.getAnswer[Boolean](SessionKeys.isFindOutHowToAppeal).isEmpty) {
```suggestion
      ) {
```

2024-01-05 14:20 UTC, AndrewRButcher commented on app/navigation/Navigation.scala
>      }
```suggestion
      Call("GET", appConfig.penaltiesFrontendUrl)
```

2024-01-05 14:20 UTC, AndrewRButcher commented on app/navigation/Navigation.scala
>      }
```suggestion
      routes.ReasonableExcuseController.onPageLoad()
```

2024-01-05 14:20 UTC, AndrewRButcher commented on app/navigation/Navigation.scala
>      } else {
remove lines 300 to 302 and 392

2024-01-05 14:20 UTC, AndrewRButcher commented on app/navigation/Navigation.scala
> +      && userRequest.answers.getAnswer[Boolean](SessionKeys.isFindOutHowToAppeal).isEmpty) {
```suggestion
      ) {
```

2024-01-05 15:12 UTC, AndrewRButcher commented on app/navigation/Navigation.scala
>      } else {
Essentially yes (the line numbers maybe off but the `if (isObligationAppeal/isFindOutHowToAppeal...` part is no longer required only users on an reasonable excuse journey can access the late appeal page so no need for the if statement

2024-01-09 15:26 UTC, JBlacklaws approved these changes
LGTM

2024-01-09 15:29 UTC, merged