PRM-446 Added for bereavement reason 'when did the person die' page
hmrc/penalties-appeals-frontend pull request #86
Opened 2021-07-21 13:15 UTC by ruthdas03

2021-07-21 14:23 UTC, LewisMitchell requested changes
Looks good, just a few changes. AT's fine.

2021-07-21 15:05 UTC, ruthdas03 commented on conf/app.routes
> +POST       /when-did-the-person-die/change              controllers.BereavementReasonController.onSubmitForWhenThePersonDied(mode: Mode = CheckMode)
Removed duplicate routes.

2021-07-21 15:06 UTC, ruthdas03 commented on it/controllers/BereavementReasonControllerISpec.scala
> +
Added /POST for /when-did-the-person-die and in the POST added the SEE_OTHER with Location "#"

2021-07-21 15:07 UTC, ruthdas03 commented on test/controllers/BereavementReasonControllerSpec.scala
> +
Added the above change for MakingALateAppeal route and Location is "#" (for now)

2021-07-22 08:25 UTC, LewisMitchell commented
![image](https://user-images.githubusercontent.com/53828896/126610048-835098c7-e282-4733-a8c9-217b95050d44.png)

2021-07-22 08:26 UTC, LewisMitchell approved these changes
Looks good to me. AT's pass with rebase

2021-07-22 08:26 UTC, merged